version: '3'
services:
  teamcity-server:
    image: jetbrains/teamcity-server:2018.2.2
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - "/home/rushan/Teamcity/data/teamcity_server/datadir:/data/teamcity_server/datadir"
      - "/home/rushan/Teamcity/opt/teamcity/logs:/opt/teamcity/logs"

  teamcity-agent:
    image: jetbrains/teamcity-agent:2018.2.2-linux
    volumes:
      - "/home/rushan/Teamcity/data/teamcity_agent/conf:/data/teamcity_agent/conf"
    environment:
      SERVER_URL: 'http://teamcity-server:8111'

